project:
  name: go-coverage
  binary: go-coverage
  module: github.com/mrz1836/go-coverage
  main: ./cmd/go-coverage/main.go

build:
  # Custom ldflags with version injection
  ldflags:
    - "-s -w"
    - "-X main.version={{.Version}}"
    - "-X main.commit={{.Commit}}"
    - "-X main.buildDate={{.Date}}"
  flags:
    - "-trimpath"
  output: "./cmd/go-coverage"
